name: create and push docker image

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    # steps:
    #   - name: Checkout code
    #     uses: actions/checkout@v4

    #   - name: Log in to Docker Hub
    #     uses: docker/login-action@v3
    #     with:
    #       username: abhishekg2244
    #       password: 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
    # steps:
    #     - name: Login
    #       uses: docker/login-action@v3
    #       with:
    #         username: ${{ github.actor }}
    #         password: ${{ secrets.GHCR_PAT }}
    steps:
    
     - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: abhishekg2244
          password: ${{ secrets.GHCR_PAT }}
