name: create and pushdockerImage

on:
  push:
    branches: [ "main" ]
 

jobs:

  build:

    runs-on: self-hosted

   
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
