name: create and push docker image

on:  workflow_dispatch
  

jobs:
  dockerLogin:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: abhishekg2244  # or ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}
          
  dockerbuildandpush:
    runs-on: self-hosted
    steps:
      - name: Build and Push Docker Image to GHCR
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: ghcr.io/${{ github.actor }}/myapp
          tags: latest
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }} 
